### ISSUE TITLE
DependsOn not working anymore

### ISSUE THREAD

**Issue by BoiteBeet** [greg0x46/laravel-nova-masked-field#2]
Need to be rebuilt with the latest version of Nova (4.32+) to work again.

**Comment by greg0x46** [comment]
Hey there, my Nova license expired on November 2, 2023, which means the last version I have access to is [v4.29.2](https://nova.laravel.com/releases/4.29.2).

Unfortunately, I don't have plans to renew it at the moment, so regrettably, I won't be able to assist you with this issue.
